spring:
  application:
    name: management-center
#  webflux:
#    base-path: /${spring.application.name}

server:
  port: 9010
  servlet:
    context-path: /${spring.application.name}



#监控，访问路径 {ip}:{port}/actuator
management:
  server:
    port: 9910

logging:
  file:
    path: @ce.log.base.dir@/${spring.application.name}

