spring:
  application:
    name: management-center
#  webflux:
#    base-path: /${spring.application.name}
  mvc:
    pathmatch:
       matching-strategy: ANT_PATH_MATCHER
  #       国际化配置
  messages:
    basename: i18n.messages,i18n.commons
    encoding: UTF-8

server:
  port: 9010
  servlet:
    context-path: /${spring.application.name}
  web:
    resources:
      static-locations: classpath:/static/,classpath:/templates/
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#监控，访问路径 {ip}:{port}/actuator
management:
  server:
    port: 9910

logging:
  file:
    path: @ce.log.base.dir@/${spring.application.name}

