spring:
  application:
    name: gateway

server:
  port: 9000

#监控，访问路径 {ip}:{port}/actuator
management:
  server:
    port: 9900
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
#          - env
#          - heapdump


logging:
  file:
    path: @ce.log.base.dir@/${spring.application.name}
